# generated by datamodel-codegen:
#   filename:  openapi.json

from __future__ import annotations
from typing import Annotated, Any, Literal
from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel
from datetime import date


class AlertEventOut(BaseModel):
    """
    A fired alert instance.
    """

    body: Annotated[str, Field(title='Body')]
    context: Annotated[dict[str, Any], Field(title='Context')]
    delivered: Annotated[bool, Field(title='Delivered')]
    id: Annotated[int, Field(title='Id')]
    rule_id: Annotated[int, Field(title='Rule Id')]
    severity: Annotated[str, Field(title='Severity')]
    title: Annotated[str, Field(title='Title')]
    ts: Annotated[str, Field(title='Ts')]


class CritThreshold(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: Annotated[
        str, Field(pattern='^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$', title='Crit Threshold')
    ]


class Threshold(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: Annotated[
        str, Field(pattern='^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$', title='Threshold')
    ]


class WarnThreshold(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: Annotated[
        str, Field(pattern='^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$', title='Warn Threshold')
    ]


class WindowKind(RootModel[str]):
    root: Annotated[str, Field(max_length=50, title='Window Kind')]


class AlertRuleIn(BaseModel):
    """
    Create/update payload for an alert rule.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    channels: Annotated[list[str] | None, Field(title='Channels')] = None
    config: Annotated[dict[str, Any] | None, Field(title='Config')] = None
    cooldown_seconds: Annotated[int | None, Field(ge=0, title='Cooldown Seconds')] = (
        3600
    )
    crit_threshold: Annotated[
        float | CritThreshold | None, Field(title='Crit Threshold')
    ] = None
    enabled: Annotated[bool | None, Field(title='Enabled')] = True
    kind: Annotated[str, Field(max_length=50, min_length=1, title='Kind')]
    name: Annotated[str, Field(max_length=200, min_length=1, title='Name')]
    quiet_hours: Annotated[dict[str, Any] | None, Field(title='Quiet Hours')] = None
    threshold: Annotated[float | Threshold | None, Field(title='Threshold')] = None
    warn_threshold: Annotated[
        float | WarnThreshold | None, Field(title='Warn Threshold')
    ] = None
    window_kind: Annotated[WindowKind | None, Field(title='Window Kind')] = None


class AlertRuleOut(BaseModel):
    """
    An alert rule as returned by the API.
    """

    channels: Annotated[list[str], Field(title='Channels')]
    config: Annotated[dict[str, Any], Field(title='Config')]
    cooldown_seconds: Annotated[int, Field(title='Cooldown Seconds')]
    crit_threshold: Annotated[CritThreshold | None, Field(title='Crit Threshold')]
    enabled: Annotated[bool, Field(title='Enabled')]
    id: Annotated[int, Field(title='Id')]
    kind: Annotated[str, Field(title='Kind')]
    last_fired_at: Annotated[str | None, Field(title='Last Fired At')]
    name: Annotated[str, Field(title='Name')]
    quiet_hours: Annotated[dict[str, Any] | None, Field(title='Quiet Hours')]
    state: Annotated[str, Field(title='State')]
    threshold: Annotated[Threshold | None, Field(title='Threshold')]
    warn_threshold: Annotated[WarnThreshold | None, Field(title='Warn Threshold')]
    window_kind: Annotated[str | None, Field(title='Window Kind')]


class AnomalyOut(BaseModel):
    """
    One flagged session and why it stood out.
    """

    cache_hit_rate: Annotated[float, Field(title='Cache Hit Rate')]
    cost_usd: Annotated[float | None, Field(title='Cost Usd')]
    project: Annotated[str | None, Field(title='Project')]
    reasons: Annotated[list[str], Field(title='Reasons')]
    session_id: Annotated[str, Field(title='Session Id')]
    severity_score: Annotated[float, Field(title='Severity Score')]
    total_tokens: Annotated[int, Field(title='Total Tokens')]


class AnomalyReportOut(BaseModel):
    """
    Anomaly-detection result across the account's sessions.
    """

    anomalies: Annotated[list[AnomalyOut], Field(title='Anomalies')]
    enough_data: Annotated[bool, Field(title='Enough Data')]
    session_count: Annotated[int, Field(title='Session Count')]


class CostUsd(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: Annotated[
        str, Field(pattern='^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$', title='Cost Usd')
    ]


class AttemptOut(BaseModel):
    """
    One final attempt event with lifecycle and usage fields (FR-QUERY-002).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    cache_read_tokens: Annotated[int, Field(title='Cache Read Tokens')]
    cache_write_long_tokens: Annotated[int, Field(title='Cache Write Long Tokens')]
    cache_write_short_tokens: Annotated[int, Field(title='Cache Write Short Tokens')]
    cost_usd: Annotated[CostUsd | None, Field(title='Cost Usd')]
    event_id: Annotated[str, Field(title='Event Id')]
    input_tokens: Annotated[int, Field(title='Input Tokens')]
    latency_ms: Annotated[int | None, Field(title='Latency Ms')]
    logical_request_id: Annotated[str | None, Field(title='Logical Request Id')]
    native_model: Annotated[str, Field(title='Native Model')]
    output_tokens: Annotated[int, Field(title='Output Tokens')]
    provider: Annotated[str, Field(title='Provider')]
    reasoning_tokens: Annotated[int, Field(title='Reasoning Tokens')]
    requested_model: Annotated[str | None, Field(title='Requested Model')]
    routed_model: Annotated[str | None, Field(title='Routed Model')]
    session_id: Annotated[str | None, Field(title='Session Id')]
    source: Annotated[str, Field(title='Source')]
    success: Annotated[bool, Field(title='Success')]
    ts_completed: Annotated[str | None, Field(title='Ts Completed')]
    ts_started: Annotated[str, Field(title='Ts Started')]


class AttemptsResponse(BaseModel):
    """
    A keyset-paginated page of attempt events.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    attempts: Annotated[list[AttemptOut], Field(title='Attempts')]
    next_cursor: Annotated[str | None, Field(title='Next Cursor')] = None


class BlockOut(BaseModel):
    """
    One reconstructed 5-hour usage block.
    """

    cost_usd: Annotated[CostUsd | None, Field(title='Cost Usd')]
    end: Annotated[str, Field(title='End')]
    end_utilization_pct: Annotated[float | None, Field(title='End Utilization Pct')]
    peak_tokens_per_min: Annotated[int, Field(title='Peak Tokens Per Min')]
    start: Annotated[str, Field(title='Start')]
    total_tokens: Annotated[int, Field(title='Total Tokens')]


class ChannelConfigIn(BaseModel):
    """
    Editable channel fields; absent field = unchanged, "" = clear to env.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    dashboard_url: Annotated[str | None, Field(title='Dashboard Url')] = None
    ntfy_topic: Annotated[str | None, Field(title='Ntfy Topic')] = None
    ntfy_url: Annotated[str | None, Field(title='Ntfy Url')] = None
    smtp_from: Annotated[str | None, Field(title='Smtp From')] = None
    smtp_host: Annotated[str | None, Field(title='Smtp Host')] = None
    smtp_password: Annotated[str | None, Field(title='Smtp Password')] = None
    smtp_port: Annotated[str | None, Field(title='Smtp Port')] = None
    smtp_to: Annotated[str | None, Field(title='Smtp To')] = None
    smtp_use_tls: Annotated[str | None, Field(title='Smtp Use Tls')] = None
    smtp_user: Annotated[str | None, Field(title='Smtp User')] = None
    telegram_bot_token: Annotated[str | None, Field(title='Telegram Bot Token')] = None
    telegram_chat_id: Annotated[str | None, Field(title='Telegram Chat Id')] = None


class ChannelFieldOut(BaseModel):
    """
    One channel config field as shown in the UI (secrets masked).
    """

    is_secret: Annotated[bool, Field(title='Is Secret')]
    is_set: Annotated[bool, Field(title='Is Set')]
    name: Annotated[str, Field(title='Name')]
    value: Annotated[str, Field(title='Value')]


class ChannelOut(BaseModel):
    """
    A notification channel's configured state and (masked) fields.
    """

    configured: Annotated[bool, Field(title='Configured')]
    fields: Annotated[list[ChannelFieldOut], Field(title='Fields')]
    name: Annotated[str, Field(title='Name')]


class ChannelsResponse(BaseModel):
    """
    All notification channels' current configuration.
    """

    channels: Annotated[list[ChannelOut], Field(title='Channels')]


class CostRowOut(BaseModel):
    """
    One grouped cost aggregate: dual metrics never merged (FR-COST-012).
    """

    model_config = ConfigDict(
        extra='forbid',
        regex_engine="python-re",
    )
    actual_spend_usd: Annotated[
        str,
        Field(pattern='^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$', title='Actual Spend Usd'),
    ]
    cost_estimated_usd: Annotated[
        str,
        Field(pattern='^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$', title='Cost Estimated Usd'),
    ]
    cost_partial_usd: Annotated[
        str,
        Field(pattern='^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$', title='Cost Partial Usd'),
    ]
    cost_priced_usd: Annotated[
        str, Field(pattern='^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$', title='Cost Priced Usd')
    ]
    key: Annotated[str, Field(title='Key')]
    pricing_version: Annotated[str, Field(title='Pricing Version')]
    subscription_value_usd: Annotated[
        str,
        Field(
            pattern='^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$', title='Subscription Value Usd'
        ),
    ]
    unpriced_event_count: Annotated[int, Field(title='Unpriced Event Count')]


class DailyAggregateIn(BaseModel):
    """
    One bootstrap daily aggregate as sent by a collector.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    cache_read_tokens: Annotated[int | None, Field(ge=0, title='Cache Read Tokens')] = 0
    cache_write_long_tokens: Annotated[
        int | None, Field(ge=0, title='Cache Write Long Tokens')
    ] = 0
    cache_write_short_tokens: Annotated[
        int | None, Field(ge=0, title='Cache Write Short Tokens')
    ] = 0
    day: Annotated[date, Field(title='Day')]
    input_tokens: Annotated[int | None, Field(ge=0, title='Input Tokens')] = 0
    message_count: Annotated[int | None, Field(ge=0, title='Message Count')] = 0
    native_model: Annotated[
        str, Field(max_length=200, min_length=1, title='Native Model')
    ]
    output_tokens: Annotated[int | None, Field(ge=0, title='Output Tokens')] = 0
    provider: Annotated[str, Field(max_length=50, min_length=1, title='Provider')]
    total_tokens: Annotated[int | None, Field(ge=0, title='Total Tokens')] = 0


class DataQualityEventOut(BaseModel):
    """
    One recorded data-quality anomaly.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    detail: Annotated[dict[str, Any], Field(title='Detail')]
    id: Annotated[int, Field(title='Id')]
    kind: Annotated[str, Field(title='Kind')]
    resolved: Annotated[bool, Field(title='Resolved')]
    source_id: Annotated[str | None, Field(title='Source Id')]
    subject: Annotated[str, Field(title='Subject')]
    ts: Annotated[str, Field(title='Ts')]


class DataQualityResponse(BaseModel):
    """
    A keyset-paginated page of data-quality events.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    events: Annotated[list[DataQualityEventOut], Field(title='Events')]
    next_cursor: Annotated[str | None, Field(title='Next Cursor')] = None


class DimensionRowOut(BaseModel):
    """
    Per-project or per-machine optimization rollup.
    """

    cache_hit_rate: Annotated[float, Field(title='Cache Hit Rate')]
    generation_share: Annotated[float, Field(title='Generation Share')]
    median_tokens_per_turn: Annotated[float, Field(title='Median Tokens Per Turn')]
    name: Annotated[str, Field(title='Name')]
    output_per_turn: Annotated[float, Field(title='Output Per Turn')]
    session_count: Annotated[int, Field(title='Session Count')]
    sidechain_share: Annotated[float, Field(title='Sidechain Share')]
    total_tokens: Annotated[int, Field(title='Total Tokens')]


class EvaluateResult(BaseModel):
    """
    Summary of a manual evaluation run.
    """

    fired: Annotated[list[AlertEventOut], Field(title='Fired')]


class EventKind(
    RootModel[Literal['attempt', 'logical_request', 'import', 'adjustment']]
):
    root: Annotated[
        Literal['attempt', 'logical_request', 'import', 'adjustment'],
        Field(
            description='What a v2 event record represents (FR-EVENT-003).\n\nATTEMPT: one upstream provider attempt -- the only billable kind\n    (FR-EVENT-004).\nLOGICAL_REQUEST: a summary grouping the attempts of one logical request.\nIMPORT: a record brought in from an external dataset or backfill.\nADJUSTMENT: an administrative correction to earlier usage.',
            title='EventKind',
        ),
    ]


class Finality(RootModel[Literal['snapshot', 'final']]):
    root: Annotated[
        Literal['snapshot', 'final'],
        Field(
            description='Whether an event is an in-progress snapshot or a terminal state.\n\nSNAPSHOT: a partial, still-changing view (for example a streamed response\n    mid-flight); superseded by a higher sequence or a final event.\nFINAL: the terminal state; supersedes any snapshot and only changes again\n    through an explicit correction (FR-IDEMP-004/005).',
            title='Finality',
        ),
    ]


class NewPrice(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: Annotated[
        str, Field(pattern='^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$', title='New Price')
    ]


class ImportChangeOut(BaseModel):
    """
    One row's effect in an import diff (new/superseded/unchanged/conflict).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    action: Annotated[str, Field(title='Action')]
    native_model: Annotated[str, Field(title='Native Model')]
    new_price: Annotated[NewPrice | None, Field(title='New Price')] = None
    priority: Annotated[int, Field(title='Priority')]
    provider: Annotated[str, Field(title='Provider')]
    unit_type: Annotated[str, Field(title='Unit Type')]


class ImportRequest(BaseModel):
    """
    Apply a rate-card import; ``digest`` is required to apply a dry run.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    digest: Annotated[str | None, Field(title='Digest')] = None


class ImportResponse(BaseModel):
    """
    A rate-card import dry-run diff or apply result (D-015).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    changes: Annotated[list[ImportChangeOut], Field(title='Changes')]
    conflicts: Annotated[int, Field(title='Conflicts')]
    digest: Annotated[str, Field(title='Digest')]
    dry_run: Annotated[bool, Field(title='Dry Run')]
    new: Annotated[int, Field(title='New')]
    superseded: Annotated[int, Field(title='Superseded')]
    unchanged: Annotated[int, Field(title='Unchanged')]


class IngestEventsResponse(BaseModel):
    """
    Result of a successful ``POST /api/v2/ingest/events`` batch.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    accepted: Annotated[int, Field(title='Accepted')]
    accepted_ids: Annotated[list[str] | None, Field(title='Accepted Ids')] = None
    batch_id: Annotated[str, Field(title='Batch Id')]
    corrected: Annotated[int, Field(title='Corrected')]
    duplicate: Annotated[int, Field(title='Duplicate')]
    ids_truncated: Annotated[bool | None, Field(title='Ids Truncated')] = False
    rejected: Annotated[int, Field(title='Rejected')]
    request_id: Annotated[str | None, Field(title='Request Id')]
    updated: Annotated[int, Field(title='Updated')]
    updated_ids: Annotated[list[str] | None, Field(title='Updated Ids')] = None


class IngestResult(BaseModel):
    """
    Outcome of an ingest call.
    """

    accepted: Annotated[int, Field(title='Accepted')]
    duplicates_merged: Annotated[int | None, Field(title='Duplicates Merged')] = 0


class LimitOut(BaseModel):
    """
    Current or historical limit utilization.
    """

    age_seconds: Annotated[int | None, Field(title='Age Seconds')] = 0
    derived_reset: Annotated[bool | None, Field(title='Derived Reset')] = False
    provenance: Annotated[str, Field(title='Provenance')]
    provider: Annotated[str, Field(title='Provider')]
    resets_at: Annotated[str | None, Field(title='Resets At')]
    ts: Annotated[str, Field(title='Ts')]
    utilization_pct: Annotated[float, Field(title='Utilization Pct')]
    window_kind: Annotated[str, Field(title='Window Kind')]


class LimitAmount(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: Annotated[
        str, Field(pattern='^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$', title='Limit Amount')
    ]


class Remaining(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: Annotated[
        str, Field(pattern='^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$', title='Remaining')
    ]


class LimitSnapshotOut(BaseModel):
    """
    One limit-utilization snapshot with its provenance (FR-LIMIT-004).

    The v2 dimensions (account/organization/source_id) and measures
    (limit_amount/remaining/unit) are null for v1 and dimension-less snapshots.
    """

    model_config = ConfigDict(
        extra='forbid',
        regex_engine="python-re",
    )
    account: Annotated[str | None, Field(title='Account')] = None
    id: Annotated[int, Field(title='Id')]
    limit_amount: Annotated[LimitAmount | None, Field(title='Limit Amount')] = None
    machine: Annotated[str | None, Field(title='Machine')]
    organization: Annotated[str | None, Field(title='Organization')] = None
    provenance: Annotated[str, Field(title='Provenance')]
    provider: Annotated[str, Field(title='Provider')]
    remaining: Annotated[Remaining | None, Field(title='Remaining')] = None
    resets_at: Annotated[str | None, Field(title='Resets At')]
    source_id: Annotated[int | None, Field(title='Source Id')] = None
    ts: Annotated[str, Field(title='Ts')]
    unit: Annotated[str | None, Field(title='Unit')] = None
    utilization_pct: Annotated[
        str, Field(pattern='^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$', title='Utilization Pct')
    ]
    window_kind: Annotated[str, Field(title='Window Kind')]


class LimitAmount1(RootModel[float]):
    root: Annotated[float, Field(ge=0.0, title='Limit Amount')] = None


class Remaining1(RootModel[float]):
    root: Annotated[float, Field(ge=0.0, title='Remaining')] = None


class LimitStreamOut(BaseModel):
    """
    The stream a forecast was computed from (its source data, FR-LIMIT-008).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    account: Annotated[str | None, Field(title='Account')]
    organization: Annotated[str | None, Field(title='Organization')]
    provider: Annotated[str, Field(title='Provider')]
    source_id: Annotated[int | None, Field(title='Source Id')]
    window_kind: Annotated[str, Field(title='Window Kind')]


class LimitsResponse(BaseModel):
    """
    A keyset-paginated page of limit snapshots.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    limits: Annotated[list[LimitSnapshotOut], Field(title='Limits')]
    next_cursor: Annotated[str | None, Field(title='Next Cursor')] = None


class CollectorVersion(RootModel[str]):
    root: Annotated[str, Field(max_length=50, title='Collector Version')]


class Platform(RootModel[str]):
    root: Annotated[str, Field(max_length=50, title='Platform')]


class MachineInfo(BaseModel):
    """
    Identifying information for the reporting machine.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    collector_version: Annotated[
        CollectorVersion | None, Field(title='Collector Version')
    ] = None
    name: Annotated[str, Field(max_length=200, min_length=1, title='Name')]
    platform: Annotated[Platform | None, Field(title='Platform')] = None


class MachineOut(BaseModel):
    """
    Fleet-view machine summary.
    """

    collector_version: Annotated[str | None, Field(title='Collector Version')]
    event_count: Annotated[int, Field(title='Event Count')]
    id: Annotated[str, Field(title='Id')]
    last_seen: Annotated[str | None, Field(title='Last Seen')]
    platform: Annotated[str | None, Field(title='Platform')]
    total_tokens: Annotated[int, Field(title='Total Tokens')]


class MetaIngestResponse(BaseModel):
    """
    Result of the v2 limits and aggregates ingest endpoints.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    accepted: Annotated[int, Field(title='Accepted')]
    batch_id: Annotated[str, Field(title='Batch Id')]
    request_id: Annotated[str | None, Field(title='Request Id')]


class ModelOut(BaseModel):
    """
    Registry metadata for one model, with its alias spellings (FR-MODEL-010).

    ``native_model_id`` is the provider's own id; ``aliases`` are the alternate
    spellings that normalize to it, so consumers see both the native and the
    normalized forms where both exist.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    aliases: Annotated[list[str], Field(title='Aliases')]
    capabilities: Annotated[dict[str, Any], Field(title='Capabilities')]
    first_seen: Annotated[str | None, Field(title='First Seen')]
    last_seen: Annotated[str | None, Field(title='Last Seen')]
    lifecycle: Annotated[str, Field(title='Lifecycle')]
    native_model_id: Annotated[str, Field(title='Native Model Id')]
    provider: Annotated[str, Field(title='Provider')]


class OverviewOut(BaseModel):
    """
    All-time totals for the dashboard summary strip.
    """

    cache_read_tokens: Annotated[int, Field(title='Cache Read Tokens')]
    cache_write_long_tokens: Annotated[int, Field(title='Cache Write Long Tokens')]
    cache_write_short_tokens: Annotated[int, Field(title='Cache Write Short Tokens')]
    cost_usd: Annotated[CostUsd | None, Field(title='Cost Usd')]
    first_event: Annotated[str | None, Field(title='First Event')]
    input_tokens: Annotated[int, Field(title='Input Tokens')]
    last_event: Annotated[str | None, Field(title='Last Event')]
    machine_count: Annotated[int, Field(title='Machine Count')]
    output_tokens: Annotated[int, Field(title='Output Tokens')]
    session_count: Annotated[int, Field(title='Session Count')]
    total_tokens: Annotated[int, Field(title='Total Tokens')]


class PredictionOut(BaseModel):
    """
    Extrapolated exhaustion for a limit window.
    """

    predicted_exhaustion_at: Annotated[
        str | None, Field(title='Predicted Exhaustion At')
    ]
    resets_at: Annotated[str | None, Field(title='Resets At')]
    slope_pct_per_min: Annotated[float, Field(title='Slope Pct Per Min')]
    utilization_pct: Annotated[float, Field(title='Utilization Pct')]
    window_kind: Annotated[str, Field(title='Window Kind')]


class CacheReadPerMtok(RootModel[float]):
    root: Annotated[float, Field(ge=0.0, title='Cache Read Per Mtok')]


class CacheReadPerMtok1(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: Annotated[
        str,
        Field(pattern='^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$', title='Cache Read Per Mtok'),
    ]


class CacheWriteLongPerMtok(RootModel[float]):
    root: Annotated[float, Field(ge=0.0, title='Cache Write Long Per Mtok')]


class CacheWriteLongPerMtok1(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: Annotated[
        str,
        Field(
            pattern='^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title='Cache Write Long Per Mtok',
        ),
    ]


class CacheWriteShortPerMtok(RootModel[float]):
    root: Annotated[float, Field(ge=0.0, title='Cache Write Short Per Mtok')]


class CacheWriteShortPerMtok1(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: Annotated[
        str,
        Field(
            pattern='^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title='Cache Write Short Per Mtok',
        ),
    ]


class InputPerMtok(RootModel[float]):
    root: Annotated[float, Field(ge=0.0, title='Input Per Mtok')]


class InputPerMtok1(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: Annotated[
        str, Field(pattern='^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$', title='Input Per Mtok')
    ]


class OutputPerMtok(RootModel[float]):
    root: Annotated[float, Field(ge=0.0, title='Output Per Mtok')]


class OutputPerMtok1(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: Annotated[
        str, Field(pattern='^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$', title='Output Per Mtok')
    ]


class PriceRowIn(BaseModel):
    """
    A price row to create or override.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    cache_read_per_mtok: Annotated[
        CacheReadPerMtok | CacheReadPerMtok1, Field(title='Cache Read Per Mtok')
    ]
    cache_write_long_per_mtok: Annotated[
        CacheWriteLongPerMtok | CacheWriteLongPerMtok1,
        Field(title='Cache Write Long Per Mtok'),
    ]
    cache_write_short_per_mtok: Annotated[
        CacheWriteShortPerMtok | CacheWriteShortPerMtok1,
        Field(title='Cache Write Short Per Mtok'),
    ]
    effective_date: Annotated[date, Field(title='Effective Date')]
    input_per_mtok: Annotated[
        InputPerMtok | InputPerMtok1, Field(title='Input Per Mtok')
    ]
    model: Annotated[str, Field(max_length=200, min_length=1, title='Model')]
    output_per_mtok: Annotated[
        OutputPerMtok | OutputPerMtok1, Field(title='Output Per Mtok')
    ]
    provider: Annotated[str, Field(max_length=50, min_length=1, title='Provider')]
    source: Annotated[str | None, Field(max_length=50, title='Source')] = 'manual'


class PricingOut(BaseModel):
    """
    A pricing table row.
    """

    model_config = ConfigDict(
        regex_engine="python-re",
    )
    cache_read_per_mtok: Annotated[
        str,
        Field(pattern='^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$', title='Cache Read Per Mtok'),
    ]
    cache_write_long_per_mtok: Annotated[
        str,
        Field(
            pattern='^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title='Cache Write Long Per Mtok',
        ),
    ]
    cache_write_short_per_mtok: Annotated[
        str,
        Field(
            pattern='^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title='Cache Write Short Per Mtok',
        ),
    ]
    effective_date: Annotated[date, Field(title='Effective Date')]
    input_per_mtok: Annotated[
        str, Field(pattern='^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$', title='Input Per Mtok')
    ]
    model: Annotated[str, Field(title='Model')]
    output_per_mtok: Annotated[
        str, Field(pattern='^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$', title='Output Per Mtok')
    ]
    provider: Annotated[str, Field(title='Provider')]
    source: Annotated[str, Field(title='Source')]


class Provenance(
    RootModel[
        Literal['official', 'local_estimate', 'stats_cache', 'imported', 'adjusted']
    ]
):
    root: Annotated[
        Literal['official', 'local_estimate', 'stats_cache', 'imported', 'adjusted'],
        Field(
            description="Origin of a number, so the UI can label official vs estimated data.\n\nOFFICIAL: read from a provider's authoritative endpoint.\nLOCAL_ESTIMATE: derived from local artifacts (for example transcripts).\nSTATS_CACHE: imported once from a provider's local aggregate cache.\nIMPORTED: brought in from an external dataset or backfill import.\nADJUSTED: written by an explicit administrative correction.\n\n``IMPORTED`` and ``ADJUSTED`` are required by the v2 event model\n(FR-EVENT-025); the first three predate it and keep their v1 meaning.",
            title='Provenance',
        ),
    ]


class PunchCell(BaseModel):
    """
    One weekday/hour cell of the punch card.
    """

    hour: Annotated[int, Field(title='Hour')]
    total_tokens: Annotated[int, Field(title='Total Tokens')]
    weekday: Annotated[int, Field(title='Weekday')]


class QueryWarningOut(BaseModel):
    """
    A data-quality caveat attached to a v2 query response (FR-QUERY-010).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    count: Annotated[int, Field(title='Count')]
    detail: Annotated[str, Field(title='Detail')]
    kind: Annotated[str, Field(title='Kind')]


class RateCardCloseRequest(BaseModel):
    """
    Close a rate card by setting its effective_to date.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    effective_to: Annotated[date, Field(title='Effective To')]


class RateCardCloseResponse(BaseModel):
    """
    The outcome of closing a rate card.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    pricing_version: Annotated[str, Field(title='Pricing Version')]
    rate_card_id: Annotated[int, Field(title='Rate Card Id')]


class UnitPrice(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: Annotated[
        str, Field(pattern='^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$', title='Unit Price')
    ]


class RateCardCreateRequest(BaseModel):
    """
    Create a rate card (manual price or override).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    context_bracket: Annotated[str | None, Field(title='Context Bracket')] = None
    currency: Annotated[str | None, Field(title='Currency')] = 'USD'
    effective_from: Annotated[date, Field(title='Effective From')]
    effective_to: Annotated[date | None, Field(title='Effective To')] = None
    mode: Annotated[str | None, Field(title='Mode')] = 'realtime'
    native_model: Annotated[str, Field(title='Native Model')]
    override: Annotated[bool | None, Field(title='Override')] = False
    priority: Annotated[int | None, Field(title='Priority')] = 0
    provider: Annotated[str, Field(title='Provider')]
    region: Annotated[str | None, Field(title='Region')] = None
    service_tier: Annotated[str | None, Field(title='Service Tier')] = None
    source: Annotated[str | None, Field(title='Source')] = 'manual'
    unit_price: Annotated[float | UnitPrice, Field(title='Unit Price')]
    unit_type: Annotated[str, Field(title='Unit Type')]


class RateCardOut(BaseModel):
    """
    One stored rate card (the v2 per-unit pricing grain).
    """

    model_config = ConfigDict(
        extra='forbid',
        regex_engine="python-re",
    )
    context_bracket: Annotated[str | None, Field(title='Context Bracket')]
    currency: Annotated[str, Field(title='Currency')]
    effective_from: Annotated[date, Field(title='Effective From')]
    effective_to: Annotated[date | None, Field(title='Effective To')]
    id: Annotated[int, Field(title='Id')]
    mode: Annotated[str, Field(title='Mode')]
    native_model: Annotated[str, Field(title='Native Model')]
    override: Annotated[bool, Field(title='Override')]
    priority: Annotated[int, Field(title='Priority')]
    provider: Annotated[str, Field(title='Provider')]
    region: Annotated[str | None, Field(title='Region')]
    service_tier: Annotated[str | None, Field(title='Service Tier')]
    source: Annotated[str, Field(title='Source')]
    unit_price: Annotated[
        str, Field(pattern='^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$', title='Unit Price')
    ]
    unit_type: Annotated[str, Field(title='Unit Type')]


class RebuildResult(BaseModel):
    """
    Outcome of a full rollup rebuild (project regrouping).
    """

    rollups_rebuilt: Annotated[int, Field(title='Rollups Rebuilt')]


class RecommendationOut(BaseModel):
    """
    One ranked optimization recommendation.
    """

    affected: Annotated[list[str], Field(title='Affected')]
    effort: Annotated[str, Field(title='Effort')]
    evidence: Annotated[str, Field(title='Evidence')]
    id: Annotated[str, Field(title='Id')]
    impact_tokens: Annotated[int | None, Field(title='Impact Tokens')]
    severity: Annotated[str, Field(title='Severity')]
    title: Annotated[str, Field(title='Title')]


class RecomputeResult(BaseModel):
    """
    Outcome of a cost recomputation.
    """

    events_updated: Annotated[int, Field(title='Events Updated')]
    rollups_refreshed: Annotated[int, Field(title='Rollups Refreshed')]


class DriftPct(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: Annotated[
        str, Field(pattern='^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$', title='Drift Pct')
    ]


class ReconciliationRowOut(BaseModel):
    """
    Observed-versus-computed cost drift for a provider (and optional day).
    """

    model_config = ConfigDict(
        extra='forbid',
        regex_engine="python-re",
    )
    computed_usd: Annotated[
        str, Field(pattern='^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$', title='Computed Usd')
    ]
    day: Annotated[str | None, Field(title='Day')] = None
    drift_pct: Annotated[DriftPct | None, Field(title='Drift Pct')] = None
    drift_usd: Annotated[
        str, Field(pattern='^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$', title='Drift Usd')
    ]
    event_count: Annotated[int, Field(title='Event Count')]
    observed_usd: Annotated[
        str, Field(pattern='^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$', title='Observed Usd')
    ]
    provider: Annotated[str, Field(title='Provider')]


class TrendItem(RootModel[tuple[str, int]]):
    root: Annotated[tuple[str, int], Field(max_length=2, min_length=2)]


class RepriceRequest(BaseModel):
    """
    Reprice a time range's costs under a new pricing version.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    end: Annotated[AwareDatetime, Field(title='End')]
    native_model: Annotated[str | None, Field(title='Native Model')] = None
    provider: Annotated[str | None, Field(title='Provider')] = None
    start: Annotated[AwareDatetime, Field(title='Start')]


class RepriceResponse(BaseModel):
    """
    The outcome of a reprice or revert operation.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    affected: Annotated[int, Field(title='Affected')]
    pricing_version: Annotated[str, Field(title='Pricing Version')]


class RequestOut(BaseModel):
    """
    A logical request with its attempt-chain aggregates (FR-TRACE-007/012).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    attempt_count: Annotated[int, Field(title='Attempt Count')]
    cost_usd: Annotated[CostUsd | None, Field(title='Cost Usd')]
    fallback_count: Annotated[int, Field(title='Fallback Count')]
    logical_request_id: Annotated[str, Field(title='Logical Request Id')]
    provider: Annotated[str, Field(title='Provider')]
    requested_model: Annotated[str | None, Field(title='Requested Model')]
    routing_policy: Annotated[str | None, Field(title='Routing Policy')]
    routing_reason: Annotated[str | None, Field(title='Routing Reason')]
    session_id: Annotated[str | None, Field(title='Session Id')]
    total_tokens: Annotated[int, Field(title='Total Tokens')]
    ts_first: Annotated[str | None, Field(title='Ts First')]
    ts_last: Annotated[str | None, Field(title='Ts Last')]
    winning_attempt_id: Annotated[str | None, Field(title='Winning Attempt Id')]


class RequestsResponse(BaseModel):
    """
    A keyset-paginated page of logical requests.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    next_cursor: Annotated[str | None, Field(title='Next Cursor')] = None
    requests: Annotated[list[RequestOut], Field(title='Requests')]


class RevertRequest(BaseModel):
    """
    Re-activate a named prior pricing version for a time range.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    end: Annotated[AwareDatetime, Field(title='End')]
    native_model: Annotated[str | None, Field(title='Native Model')] = None
    pricing_version: Annotated[str, Field(title='Pricing Version')]
    provider: Annotated[str | None, Field(title='Provider')] = None
    start: Annotated[AwareDatetime, Field(title='Start')]


class CostEstimatedUsd(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: Annotated[
        str,
        Field(pattern='^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$', title='Cost Estimated Usd'),
    ]


class CostPartialUsd(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: Annotated[
        str,
        Field(pattern='^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$', title='Cost Partial Usd'),
    ]


class CostPricedUsd(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: Annotated[
        str, Field(pattern='^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$', title='Cost Priced Usd')
    ]


class SubscriptionValueUsd(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: Annotated[
        str,
        Field(
            pattern='^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$', title='Subscription Value Usd'
        ),
    ]


class RollupOut(BaseModel):
    """
    One daily_rollups row exposed for external tooling (stable columns).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    billing_mode: Annotated[str, Field(title='Billing Mode')]
    cache_read_tokens: Annotated[int, Field(title='Cache Read Tokens')]
    cache_write_long_tokens: Annotated[int, Field(title='Cache Write Long Tokens')]
    cache_write_short_tokens: Annotated[int, Field(title='Cache Write Short Tokens')]
    cost_estimated_usd: Annotated[
        CostEstimatedUsd | None, Field(title='Cost Estimated Usd')
    ]
    cost_partial_usd: Annotated[CostPartialUsd | None, Field(title='Cost Partial Usd')]
    cost_priced_usd: Annotated[CostPricedUsd | None, Field(title='Cost Priced Usd')]
    cost_usd: Annotated[CostUsd | None, Field(title='Cost Usd')]
    day: Annotated[date, Field(title='Day')]
    environment: Annotated[str, Field(title='Environment')]
    id: Annotated[int, Field(title='Id')]
    input_tokens: Annotated[int, Field(title='Input Tokens')]
    machine: Annotated[str, Field(title='Machine')]
    model: Annotated[str, Field(title='Model')]
    output_tokens: Annotated[int, Field(title='Output Tokens')]
    project: Annotated[str, Field(title='Project')]
    provenance: Annotated[str, Field(title='Provenance')]
    provider: Annotated[str, Field(title='Provider')]
    reasoning_tokens: Annotated[int, Field(title='Reasoning Tokens')]
    source: Annotated[str, Field(title='Source')]
    subscription_value_usd: Annotated[
        SubscriptionValueUsd | None, Field(title='Subscription Value Usd')
    ]
    total_tokens: Annotated[int, Field(title='Total Tokens')]
    unpriced_event_count: Annotated[int, Field(title='Unpriced Event Count')]


class RollupsResponse(BaseModel):
    """
    A keyset-paginated page of daily rollup rows.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    next_cursor: Annotated[str | None, Field(title='Next Cursor')] = None
    rollups: Annotated[list[RollupOut], Field(title='Rollups')]


class AttemptIndex(RootModel[int]):
    root: Annotated[int, Field(ge=0, title='Attempt Index')] = None


class Routing(BaseModel):
    """
    Gateway-neutral routing metadata for one attempt (FR-EVENT-019).

    Optional and provider-agnostic: a gateway that cascades across models
    records the policy that chose a model, why it was chosen, this attempt's
    index in the chain, and -- for a fallback -- which model it fell back from
    and what triggered the fallback. Gateway-specific detail beyond these
    fields belongs in ``UsageEventV2.extra`` under a namespaced key.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    attempt_index: Annotated[AttemptIndex | None, Field(title='Attempt Index')] = None
    fallback_from: Annotated[str | None, Field(title='Fallback From')] = None
    fallback_trigger: Annotated[str | None, Field(title='Fallback Trigger')] = None
    policy: Annotated[str | None, Field(title='Policy')] = None
    reason: Annotated[str | None, Field(title='Reason')] = None


class TopModel(RootModel[tuple[str, float]]):
    root: Annotated[tuple[str, float], Field(max_length=2, min_length=2)]


class ScorecardOut(BaseModel):
    """
    Global optimization scorecard.
    """

    cache_hit_rate: Annotated[float, Field(title='Cache Hit Rate')]
    cache_read_tokens: Annotated[int, Field(title='Cache Read Tokens')]
    cache_write_tokens: Annotated[int, Field(title='Cache Write Tokens')]
    generation_share: Annotated[float, Field(title='Generation Share')]
    input_tokens: Annotated[int, Field(title='Input Tokens')]
    machine_count: Annotated[int, Field(title='Machine Count')]
    median_tokens_per_turn: Annotated[float, Field(title='Median Tokens Per Turn')]
    output_per_turn: Annotated[float, Field(title='Output Per Turn')]
    output_tokens: Annotated[int, Field(title='Output Tokens')]
    session_count: Annotated[int, Field(title='Session Count')]
    sidechain_share: Annotated[float, Field(title='Sidechain Share')]
    top_models: Annotated[list[TopModel], Field(title='Top Models')]
    total_tokens: Annotated[int, Field(title='Total Tokens')]
    total_turns: Annotated[int, Field(title='Total Turns')]
    unattributed_share: Annotated[float, Field(title='Unattributed Share')]


class SessionEventOut(BaseModel):
    """
    One usage event in a session drill-down (metadata only).
    """

    cache_read_tokens: Annotated[int, Field(title='Cache Read Tokens')]
    cache_write_long_tokens: Annotated[int, Field(title='Cache Write Long Tokens')]
    cache_write_short_tokens: Annotated[int, Field(title='Cache Write Short Tokens')]
    cost_usd: Annotated[CostUsd | None, Field(title='Cost Usd')]
    input_tokens: Annotated[int, Field(title='Input Tokens')]
    model: Annotated[str, Field(title='Model')]
    output_tokens: Annotated[int, Field(title='Output Tokens')]
    total_tokens: Annotated[int, Field(title='Total Tokens')]
    ts: Annotated[str, Field(title='Ts')]


class SessionStatsOut(BaseModel):
    """
    Derived efficiency signals for a session.
    """

    cache_hit_rate: Annotated[float, Field(title='Cache Hit Rate')]
    context_growth: Annotated[float, Field(title='Context Growth')]
    inflection_index: Annotated[int | None, Field(title='Inflection Index')]
    tokens_per_turn: Annotated[float, Field(title='Tokens Per Turn')]


class SourceHealthOut(BaseModel):
    """
    Query-time health of a reporting source (FR-SOURCE-005).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    clock_skew_seconds: Annotated[float | None, Field(title='Clock Skew Seconds')]
    last_successful_ingest: Annotated[str | None, Field(title='Last Successful Ingest')]
    recent_error_count: Annotated[int, Field(title='Recent Error Count')]
    reported_schema_version: Annotated[
        int | None, Field(title='Reported Schema Version')
    ]
    stale: Annotated[bool, Field(title='Stale')]
    staleness_threshold_seconds: Annotated[
        float, Field(title='Staleness Threshold Seconds')
    ]


class SourceOut(BaseModel):
    """
    A reporting source with its health (FR-SOURCE-001..006). No secrets.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    billing_mode: Annotated[str, Field(title='Billing Mode')]
    first_seen: Annotated[str, Field(title='First Seen')]
    health: SourceHealthOut
    id: Annotated[int, Field(title='Id')]
    instance_id: Annotated[str | None, Field(title='Instance Id')]
    last_seen: Annotated[str, Field(title='Last Seen')]
    machine: Annotated[str | None, Field(title='Machine')]
    name: Annotated[str, Field(title='Name')]
    revoked: Annotated[bool, Field(title='Revoked')]
    token_label: Annotated[str | None, Field(title='Token Label')]
    type: Annotated[str, Field(title='Type')]
    version: Annotated[str | None, Field(title='Version')]


class SourceType(
    RootModel[Literal['collector', 'gateway', 'sdk', 'importer', 'manual']]
):
    root: Annotated[
        Literal['collector', 'gateway', 'sdk', 'importer', 'manual'],
        Field(
            description='The kind of reporting source a v2 event came from (FR-SOURCE-002).',
            title='SourceType',
        ),
    ]


class SourceUpdateRequest(BaseModel):
    """
    Mutable source fields (label and billing mode); event identity is fixed.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    billing_mode: Annotated[str | None, Field(title='Billing Mode')] = None
    token_label: Annotated[str | None, Field(title='Token Label')] = None


class SyncResult(BaseModel):
    """
    Outcome of a LiteLLM price sync.
    """

    synced: Annotated[int, Field(title='Synced')]


class TestChannelResult(BaseModel):
    """
    Outcome of a test notification to one channel.
    """

    channel: Annotated[str, Field(title='Channel')]
    delivered: Annotated[bool, Field(title='Delivered')]


class TokenCreateRequest(BaseModel):
    """
    Request to mint an API token.

    ``scopes`` default to the full set when omitted (compatibility with
    pre-scope clients); ``source_allowlist`` optionally restricts which
    reporting sources the token may ingest for.
    """

    label: Annotated[str, Field(title='Label')]
    scopes: Annotated[list[str] | None, Field(title='Scopes')] = None
    source_allowlist: Annotated[list[str] | None, Field(title='Source Allowlist')] = (
        None
    )


class TokenCreatedOut(BaseModel):
    """
    A newly created token; the secret appears only here.
    """

    created_at: Annotated[str, Field(title='Created At')]
    label: Annotated[str, Field(title='Label')]
    scopes: Annotated[list[str], Field(title='Scopes')]
    token: Annotated[str, Field(title='Token')]


class TokenInfoOut(BaseModel):
    """
    Stored token metadata (never the secret).
    """

    created_at: Annotated[str, Field(title='Created At')]
    label: Annotated[str, Field(title='Label')]
    last_used: Annotated[str | None, Field(title='Last Used')]
    revoked: Annotated[bool, Field(title='Revoked')]
    scopes: Annotated[list[str], Field(title='Scopes')]
    source_allowlist: Annotated[list[str] | None, Field(title='Source Allowlist')]


class UnknownModelReportRow(BaseModel):
    """
    An unknown-model observation recorded at ingest.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    last_seen: Annotated[str, Field(title='Last Seen')]
    native_model: Annotated[str, Field(title='Native Model')]
    observations: Annotated[int, Field(title='Observations')]
    provider: Annotated[str, Field(title='Provider')]
    resolved: Annotated[bool, Field(title='Resolved')]


class UnpricedReportRow(BaseModel):
    """
    An aggregate of unpriced or partially priced events for one model.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    cost_status: Annotated[str, Field(title='Cost Status')]
    event_count: Annotated[int, Field(title='Event Count')]
    native_model: Annotated[str, Field(title='Native Model')]
    provider: Annotated[str, Field(title='Provider')]


class UsageBucketOut(BaseModel):
    """
    Aggregated usage for one group-by key.
    """

    cache_read_tokens: Annotated[int, Field(title='Cache Read Tokens')]
    cache_write_long_tokens: Annotated[int, Field(title='Cache Write Long Tokens')]
    cache_write_short_tokens: Annotated[int, Field(title='Cache Write Short Tokens')]
    cost_usd: Annotated[CostUsd | None, Field(title='Cost Usd')]
    input_tokens: Annotated[int, Field(title='Input Tokens')]
    key: Annotated[str, Field(title='Key')]
    output_tokens: Annotated[int, Field(title='Output Tokens')]
    total_tokens: Annotated[int, Field(title='Total Tokens')]


class ClientVersion(RootModel[str]):
    root: Annotated[str, Field(max_length=50, title='Client Version')]


class Entrypoint(RootModel[str]):
    root: Annotated[str, Field(max_length=50, title='Entrypoint')]


class GitBranch(RootModel[str]):
    root: Annotated[str, Field(max_length=300, title='Git Branch')]


class Project(RootModel[str]):
    root: Annotated[str, Field(max_length=500, title='Project')]


class ServiceTier(RootModel[str]):
    root: Annotated[str, Field(max_length=50, title='Service Tier')]


class SessionId(RootModel[str]):
    root: Annotated[str, Field(max_length=200, title='Session Id')]


class SessionKind(RootModel[str]):
    root: Annotated[str, Field(max_length=50, title='Session Kind')]


class Speed(RootModel[str]):
    root: Annotated[str, Field(max_length=50, title='Speed')]


class UsageEventIn(BaseModel):
    """
    One usage event as sent by a collector.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    cache_read_tokens: Annotated[int | None, Field(ge=0, title='Cache Read Tokens')] = 0
    cache_write_long_tokens: Annotated[
        int | None, Field(ge=0, title='Cache Write Long Tokens')
    ] = 0
    cache_write_short_tokens: Annotated[
        int | None, Field(ge=0, title='Cache Write Short Tokens')
    ] = 0
    client_version: Annotated[ClientVersion | None, Field(title='Client Version')] = (
        None
    )
    entrypoint: Annotated[Entrypoint | None, Field(title='Entrypoint')] = None
    event_id: Annotated[str, Field(max_length=200, min_length=1, title='Event Id')]
    extra: Annotated[dict[str, Any] | None, Field(title='Extra')] = None
    git_branch: Annotated[GitBranch | None, Field(title='Git Branch')] = None
    input_tokens: Annotated[int | None, Field(ge=0, title='Input Tokens')] = 0
    is_sidechain: Annotated[bool | None, Field(title='Is Sidechain')] = False
    native_model: Annotated[
        str, Field(max_length=200, min_length=1, title='Native Model')
    ]
    output_tokens: Annotated[int | None, Field(ge=0, title='Output Tokens')] = 0
    project: Annotated[Project | None, Field(title='Project')] = None
    provenance: Annotated[Provenance | None, Field(validate_default=True)] = (
        'local_estimate'
    )
    provider: Annotated[str, Field(max_length=50, min_length=1, title='Provider')]
    service_tier: Annotated[ServiceTier | None, Field(title='Service Tier')] = None
    session_id: Annotated[SessionId | None, Field(title='Session Id')] = None
    session_kind: Annotated[SessionKind | None, Field(title='Session Kind')] = None
    speed: Annotated[Speed | None, Field(title='Speed')] = None
    ts: Annotated[AwareDatetime, Field(title='Ts')]


class LatencyMs(RootModel[int]):
    root: Annotated[int, Field(ge=0, title='Latency Ms')] = None


class ObservedCost(RootModel[float]):
    root: Annotated[float, Field(ge=0.0, title='Observed Cost')] = None


class ObservedCost1(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: Annotated[
        str, Field(pattern='^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$', title='Observed Cost')
    ] = None


class TimeToFirstTokenMs(RootModel[int]):
    root: Annotated[int, Field(ge=0, title='Time To First Token Ms')] = None


class UsageRowOut(BaseModel):
    """
    One grouped usage aggregate (six counters plus attempt count).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    attempt_count: Annotated[int, Field(title='Attempt Count')]
    cache_read_tokens: Annotated[int, Field(title='Cache Read Tokens')]
    cache_write_long_tokens: Annotated[int, Field(title='Cache Write Long Tokens')]
    cache_write_short_tokens: Annotated[int, Field(title='Cache Write Short Tokens')]
    input_tokens: Annotated[int, Field(title='Input Tokens')]
    key: Annotated[str, Field(title='Key')]
    output_tokens: Annotated[int, Field(title='Output Tokens')]
    reasoning_tokens: Annotated[int, Field(title='Reasoning Tokens')]
    total_tokens: Annotated[int, Field(title='Total Tokens')]


class ValidationError(BaseModel):
    ctx: Annotated[dict[str, Any] | None, Field(title='Context')] = None
    input: Annotated[Any | None, Field(title='Input')] = None
    loc: Annotated[list[str | int], Field(title='Location')]
    msg: Annotated[str, Field(title='Message')]
    type: Annotated[str, Field(title='Error Type')]


class ValidationErrorItem(BaseModel):
    """
    One structured validation failure (FR-INGEST-006).

    ``index`` is the event's position in the batch (``-1`` for a batch-envelope
    error); ``field_path`` is a dotted path into the event; ``code`` and
    ``message`` name and describe the failure. This is the stable shape the
    generated clients (task 62.12) and the exporter conformance suite consume.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    code: Annotated[str, Field(title='Code')]
    field_path: Annotated[str, Field(title='Field Path')]
    index: Annotated[int, Field(title='Index')]
    message: Annotated[str, Field(title='Message')]


class WindowOut(BaseModel):
    """
    One limit-window descriptor from the provider registry (FR-LIMIT-012).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Annotated[str, Field(title='Kind')]
    label: Annotated[str, Field(title='Label')]
    period_kind: Annotated[str, Field(title='Period Kind')]
    period_seconds: Annotated[int | None, Field(title='Period Seconds')] = None
    sort_order: Annotated[int | None, Field(title='Sort Order')] = 0


class TokemetryServerApiSchemasQueryCostResponse(BaseModel):
    """
    Cost over a range with the subscription value multiple.
    """

    model_config = ConfigDict(
        regex_engine="python-re",
    )
    end: Annotated[date, Field(title='End')]
    start: Annotated[date, Field(title='Start')]
    subscription_monthly_usd: Annotated[
        float | None, Field(title='Subscription Monthly Usd')
    ]
    total_cost_usd: Annotated[
        str, Field(pattern='^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$', title='Total Cost Usd')
    ]
    value_multiple: Annotated[float | None, Field(title='Value Multiple')]


class TokemetryServerApiSchemasQuerySessionOut(BaseModel):
    """
    Aggregated session summary.
    """

    cost_usd: Annotated[CostUsd | None, Field(title='Cost Usd')]
    last_at: Annotated[str, Field(title='Last At')]
    machine: Annotated[str | None, Field(title='Machine')]
    message_count: Annotated[int, Field(title='Message Count')]
    project: Annotated[str | None, Field(title='Project')]
    provider: Annotated[str, Field(title='Provider')]
    session_id: Annotated[str, Field(title='Session Id')]
    started_at: Annotated[str, Field(title='Started At')]
    total_tokens: Annotated[int, Field(title='Total Tokens')]


class TokemetryServerApiSchemasQueryUsageResponse(BaseModel):
    """
    Grouped usage over a range.
    """

    buckets: Annotated[list[UsageBucketOut], Field(title='Buckets')]
    end: Annotated[date, Field(title='End')]
    group_by: Annotated[str, Field(title='Group By')]
    start: Annotated[date, Field(title='Start')]


class TokemetryServerApiV2SchemasCostResponse(BaseModel):
    """
    Grouped costs with data-quality warnings (FR-QUERY-006).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    group_by: Annotated[str, Field(title='Group By')]
    rows: Annotated[list[CostRowOut], Field(title='Rows')]
    warnings: Annotated[list[QueryWarningOut], Field(title='Warnings')]


class TokemetryServerApiV2SchemasSessionOut(BaseModel):
    """
    A session rollup keyed by scoped identity (FR-TRACE-010/011).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    attempt_count: Annotated[int, Field(title='Attempt Count')]
    cost_usd: Annotated[CostUsd | None, Field(title='Cost Usd')]
    provider: Annotated[str, Field(title='Provider')]
    scoped_id: Annotated[str, Field(title='Scoped Id')]
    session_id: Annotated[str, Field(title='Session Id')]
    source: Annotated[str, Field(title='Source')]
    total_tokens: Annotated[int, Field(title='Total Tokens')]
    ts_first: Annotated[str | None, Field(title='Ts First')]
    ts_last: Annotated[str | None, Field(title='Ts Last')]


class TokemetryServerApiV2SchemasUsageResponse(BaseModel):
    """
    Grouped final-attempt usage with data-quality warnings (FR-QUERY-007).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    group_by: Annotated[str, Field(title='Group By')]
    rows: Annotated[list[UsageRowOut], Field(title='Rows')]
    warnings: Annotated[list[QueryWarningOut], Field(title='Warnings')]


class BootstrapIngest(BaseModel):
    """
    Batch of bootstrap daily aggregates from one machine.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    aggregates: Annotated[
        list[DailyAggregateIn],
        Field(max_length=20000, min_length=1, title='Aggregates'),
    ]
    machine: MachineInfo


class EventsIngest(BaseModel):
    """
    Batch of usage events from one machine.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    events: Annotated[
        list[UsageEventIn], Field(max_length=5000, min_length=1, title='Events')
    ]
    machine: MachineInfo


class HTTPValidationError(BaseModel):
    detail: Annotated[list[ValidationError] | None, Field(title='Detail')] = None


class HeatmapResponse(BaseModel):
    """
    Calendar (daily) and punch-card (weekday x hour) usage.
    """

    calendar: Annotated[list[UsageBucketOut], Field(title='Calendar')]
    punch_card: Annotated[list[PunchCell], Field(title='Punch Card')]


class LimitForecastOut(BaseModel):
    """
    An exhaustion forecast for one limit stream with confidence (FR-LIMIT-008).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    confidence: Annotated[str, Field(title='Confidence')]
    predicted_exhaustion_at: Annotated[
        str | None, Field(title='Predicted Exhaustion At')
    ]
    resets_at: Annotated[str | None, Field(title='Resets At')]
    sample_count: Annotated[int, Field(title='Sample Count')]
    slope_pct_per_min: Annotated[float, Field(title='Slope Pct Per Min')]
    stream: LimitStreamOut
    utilization_pct: Annotated[float, Field(title='Utilization Pct')]
    will_reset_first: Annotated[bool, Field(title='Will Reset First')]


class LimitForecastResponse(BaseModel):
    """
    Per-stream limit exhaustion forecasts over a range.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    forecasts: Annotated[list[LimitForecastOut], Field(title='Forecasts')]


class LimitSnapshotIn(BaseModel):
    """
    One limit-window snapshot as sent by a collector.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    provenance: Annotated[Provenance | None, Field(validate_default=True)] = 'official'
    provider: Annotated[str, Field(max_length=50, min_length=1, title='Provider')]
    raw: Annotated[dict[str, Any] | None, Field(title='Raw')] = None
    resets_at: Annotated[AwareDatetime | None, Field(title='Resets At')] = None
    ts: Annotated[AwareDatetime, Field(title='Ts')]
    utilization_pct: Annotated[float, Field(ge=0.0, title='Utilization Pct')]
    window_kind: Annotated[str, Field(max_length=50, min_length=1, title='Window Kind')]


class LimitsIngest(BaseModel):
    """
    Batch of limit snapshots from one machine.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    machine: MachineInfo
    snapshots: Annotated[
        list[LimitSnapshotIn], Field(max_length=1000, min_length=1, title='Snapshots')
    ]


class ProviderOut(BaseModel):
    """
    Registry metadata for one provider (FR-PROVIDER-010).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    aliases: Annotated[list[str], Field(title='Aliases')]
    display_name: Annotated[str, Field(title='Display Name')]
    id: Annotated[str, Field(title='Id')]
    limit_semantics: Annotated[str, Field(title='Limit Semantics')]
    pricing_strategy: Annotated[str, Field(title='Pricing Strategy')]
    registered: Annotated[bool, Field(title='Registered')]
    supported_dimensions: Annotated[list[str], Field(title='Supported Dimensions')]
    windows: Annotated[list[WindowOut], Field(title='Windows')]


class RateCardMutationResponse(BaseModel):
    """
    A created rate card plus the current pricing-state version.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    pricing_version: Annotated[str, Field(title='Pricing Version')]
    rate_card: RateCardOut


class ReconciliationResponse(BaseModel):
    """
    Cost reconciliation drift rows.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    rows: Annotated[list[ReconciliationRowOut], Field(title='Rows')]


class ReportOut(BaseModel):
    """
    The full optimization report over a range.
    """

    end: Annotated[date, Field(title='End')]
    machines: Annotated[list[DimensionRowOut], Field(title='Machines')]
    projects: Annotated[list[DimensionRowOut], Field(title='Projects')]
    recommendations: Annotated[list[RecommendationOut], Field(title='Recommendations')]
    scorecard: ScorecardOut
    start: Annotated[date, Field(title='Start')]
    trend: Annotated[list[TrendItem], Field(title='Trend')]


class RequestDetailResponse(BaseModel):
    """
    A logical request with its ordered attempts (fallback-chain drilldown).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    attempts: Annotated[list[AttemptOut], Field(title='Attempts')]
    request: RequestOut


class SessionDetailOut(BaseModel):
    """
    A session's ordered event series and derived stats.
    """

    events: Annotated[list[SessionEventOut], Field(title='Events')]
    machine: Annotated[str | None, Field(title='Machine')]
    message_count: Annotated[int, Field(title='Message Count')]
    project: Annotated[str | None, Field(title='Project')]
    session_id: Annotated[str, Field(title='Session Id')]
    stats: SessionStatsOut
    total_tokens: Annotated[int, Field(title='Total Tokens')]


class SessionsResponse(BaseModel):
    """
    A paginated page of session rollups.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    next_cursor: Annotated[str | None, Field(title='Next Cursor')] = None
    sessions: Annotated[
        list[TokemetryServerApiV2SchemasSessionOut], Field(title='Sessions')
    ]


class SourceRef(BaseModel):
    """
    Identity of the source that reported an event (FR-EVENT-018).

    Source identity is distinct from machine identity (FR-SOURCE-003): one
    machine may host several sources. ``version`` is required so source health
    can track schema/version drift; ``instance_id`` distinguishes concurrent
    instances of the same named source and is optional.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    instance_id: Annotated[str | None, Field(title='Instance Id')] = None
    name: Annotated[str, Field(min_length=1, title='Name')]
    type: SourceType
    version: Annotated[str, Field(min_length=1, title='Version')]


class TodaySummary(BaseModel):
    """
    Today's totals and per-model breakdown.
    """

    by_model: Annotated[list[UsageBucketOut], Field(title='By Model')]
    cost_usd: Annotated[CostUsd | None, Field(title='Cost Usd')]
    total_tokens: Annotated[int, Field(title='Total Tokens')]


class UsageEventV2(BaseModel):
    """
    One provider-neutral v2 usage event (PRD Section 12.3 wire shape).

    ``event_id`` is unique within the canonical provider namespace
    (FR-EVENT-002); ingest resolves revisions of the same id by ``finality``
    and ``sequence``. Token counters are non-negative and default to zero so a
    failed or cancelled attempt is ingestible with no usage (FR-EVENT-024).
    ``reasoning_tokens`` is stored apart from ``output_tokens`` (FR-EVENT-015),
    and ``success`` (did the attempt succeed) is kept separate from ``outcome``
    (the nuanced terminal state) per FR-EVENT-017.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    agent_id: Annotated[str | None, Field(title='Agent Id')] = None
    attempt_id: Annotated[str | None, Field(title='Attempt Id')] = None
    billable_units: Annotated[
        dict[str, float] | None, Field(title='Billable Units')
    ] = None
    cache_read_tokens: Annotated[int | None, Field(ge=0, title='Cache Read Tokens')] = 0
    cache_write_long_tokens: Annotated[
        int | None, Field(ge=0, title='Cache Write Long Tokens')
    ] = 0
    cache_write_short_tokens: Annotated[
        int | None, Field(ge=0, title='Cache Write Short Tokens')
    ] = 0
    dimensions: Annotated[dict[str, str] | None, Field(title='Dimensions')] = None
    environment: Annotated[str | None, Field(title='Environment')] = None
    event_id: Annotated[str, Field(min_length=1, title='Event Id')]
    event_kind: EventKind
    extra: Annotated[dict[str, Any] | None, Field(title='Extra')] = None
    finality: Finality
    http_status: Annotated[int | None, Field(title='Http Status')] = None
    input_tokens: Annotated[int | None, Field(ge=0, title='Input Tokens')] = 0
    latency_ms: Annotated[LatencyMs | None, Field(title='Latency Ms')] = None
    logical_request_id: Annotated[str | None, Field(title='Logical Request Id')] = None
    machine: Annotated[str | None, Field(title='Machine')] = None
    native_model: Annotated[str, Field(min_length=1, title='Native Model')]
    observed_cost: Annotated[
        ObservedCost | ObservedCost1 | None, Field(title='Observed Cost')
    ] = None
    outcome: Annotated[str | None, Field(title='Outcome')] = None
    output_tokens: Annotated[int | None, Field(ge=0, title='Output Tokens')] = 0
    parent_span_id: Annotated[str | None, Field(title='Parent Span Id')] = None
    project: Annotated[str | None, Field(title='Project')] = None
    provenance: Annotated[Provenance | None, Field(validate_default=True)] = (
        'local_estimate'
    )
    provider: Annotated[str, Field(min_length=1, title='Provider')]
    provider_request_id: Annotated[str | None, Field(title='Provider Request Id')] = (
        None
    )
    provider_response_id: Annotated[str | None, Field(title='Provider Response Id')] = (
        None
    )
    reasoning_tokens: Annotated[int | None, Field(ge=0, title='Reasoning Tokens')] = 0
    requested_model: Annotated[str | None, Field(title='Requested Model')] = None
    routed_model: Annotated[str | None, Field(title='Routed Model')] = None
    routing: Routing | None = None
    schema_version: Annotated[Literal[2], Field(title='Schema Version')]
    sequence: Annotated[int, Field(ge=0, title='Sequence')]
    service_tier: Annotated[str | None, Field(title='Service Tier')] = None
    session_id: Annotated[str | None, Field(title='Session Id')] = None
    source: SourceRef
    span_id: Annotated[str | None, Field(title='Span Id')] = None
    stop_reason: Annotated[str | None, Field(title='Stop Reason')] = None
    streaming: Annotated[bool | None, Field(title='Streaming')] = None
    success: Annotated[bool | None, Field(title='Success')] = False
    time_to_first_token_ms: Annotated[
        TimeToFirstTokenMs | None, Field(title='Time To First Token Ms')
    ] = None
    tool_call_count: Annotated[int | None, Field(ge=0, title='Tool Call Count')] = 0
    tool_histogram: Annotated[dict[str, int] | None, Field(title='Tool Histogram')] = (
        None
    )
    trace_id: Annotated[str | None, Field(title='Trace Id')] = None
    ts_completed: Annotated[AwareDatetime | None, Field(title='Ts Completed')] = None
    ts_first_token: Annotated[AwareDatetime | None, Field(title='Ts First Token')] = (
        None
    )
    ts_started: Annotated[AwareDatetime, Field(title='Ts Started')]


class ValidateResponse(BaseModel):
    """
    Result of ``POST /api/v2/ingest/validate`` (never persists).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    errors: Annotated[list[ValidationErrorItem], Field(title='Errors')]
    request_id: Annotated[str | None, Field(title='Request Id')]
    valid: Annotated[bool, Field(title='Valid')]


class LimitSnapshotV2(BaseModel):
    """
    A provider-neutral rate-limit window snapshot (FR-LIMIT-002..004).

    ``window_kind`` is an opaque, provider-defined label (Anthropic's
    ``five_hour``, a Codex window, a Z.ai coding-plan window), so new providers
    need no schema change. The extended dimensions -- ``account``,
    ``organization``, ``source``, ``remaining``, ``limit_amount``, ``unit`` --
    are the v2 additions over v1's utilization-only snapshot; the dedicated
    ``limit_snapshots`` columns for them land in Task 69, so until then the
    ingest endpoint preserves them in the row's ``raw`` JSON. Snapshots are
    append-only.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    account: Annotated[str | None, Field(title='Account')] = None
    limit_amount: Annotated[LimitAmount1 | None, Field(title='Limit Amount')] = None
    machine: Annotated[str | None, Field(title='Machine')] = None
    organization: Annotated[str | None, Field(title='Organization')] = None
    provenance: Annotated[Provenance | None, Field(validate_default=True)] = 'official'
    provider: Annotated[str, Field(min_length=1, title='Provider')]
    remaining: Annotated[Remaining1 | None, Field(title='Remaining')] = None
    resets_at: Annotated[AwareDatetime | None, Field(title='Resets At')] = None
    schema_version: Annotated[Literal[2], Field(title='Schema Version')]
    source: SourceRef | None = None
    ts: Annotated[AwareDatetime, Field(title='Ts')]
    unit: Annotated[str | None, Field(title='Unit')] = None
    utilization_pct: Annotated[float, Field(ge=0.0, title='Utilization Pct')]
    window_kind: Annotated[str, Field(min_length=1, title='Window Kind')]


class SummaryNow(BaseModel):
    """
    The dashboard front-page summary.
    """

    limits: Annotated[list[LimitOut], Field(title='Limits')]
    now: Annotated[str, Field(title='Now')]
    prediction: PredictionOut | None
    today: TodaySummary
    token_burn_rate_per_min: Annotated[float, Field(title='Token Burn Rate Per Min')]
